### ISSUE TITLE
Update the server side programming language

### ISSUE THREAD

**Issue by Bikash-Bhatta** [sdgniser/arc#31]
I found out that PHP is being used as the server language. Here it is of version 7, which is outdated and have bugs in them. So updating it will protect us from malicious attacks as PHP version 7 being used by many unauthorized websites so one can use those to get into this site.
**Solution**
Update the PHP version to 8.1 , current stable version is 8.1.10

**Comment by Abhishek-Deshmukh** [comment]
Hello @Bikash-Bhatta,
I believe that is factually incorrect. [NISER Archive](https://github.com/sdgniser/arc) uses the [python](https://www.python.org/) programming language as the server-side language.

![image](https://user-images.githubusercontent.com/42207326/192157736-4464d2e9-5785-4f22-87e2-3cc54580430f.png)

Regards

**Comment by Bikash-Bhatta** [comment]
@Abhishek-Deshmukh I think python is the client side programming language. If it is not php then how come it is validating php commands. Use the command in the URL "?var=True". It will show email is verified. I had also reported this issue.

**Comment by JeS24** [comment]
Arc does not use PHP. As @Abhishek-Deshmukh mentioned, Arc uses Python, in particular, the Django web framework for the backend with PostgreSQL for the database. The code that runs the site is open source and available in this repo. You are free to audit it.

That said, we are using an old version of `django` (still supported for now) due to a core dependency issue. #10 and #27 document this.
